version: '3.8'
services:
  registry:
    image: registry:3
    container_name: local-registry
    ports:
      - "5000:5000"

  k3s:
    image: rancher/k3s:v1.30.13-k3s1
    container_name: local-k3s
    privileged: true
    ports:
      - "6443:6443"
    environment:
      - K3S_CLUSTER_INIT=true
      - K3S_TOKEN=mysupersecrettoken
    command: server

