name: deno-sample-app-local-mock
services:
  registry:
    image: registry:3
    ports:
      - "5000:5000"
  k3s-server:
    image: rancher/k3s:v1.30.13-k3s1
    privileged: true
    ports:
      - "6443:6443"
    command: server
